apiVersion: v1
kind: Service
metadata:
    name: luach
    labels:
        name: luach
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3004
      protocol: TCP
    selector:
        name: luach
